version: '3.4'

services:
  db:
    image: postgres:10.5-alpine
    env_file:
      - .env.secret
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  rabbitmq:
    image: rabbitmq:3.7.12
    env_file:
      - .env.secret
    restart: always
  django:
    build:
      context: ../../
      dockerfile: ./Docker/prod/python/Dockerfile
      target: django
    command: gunicorn --workers 2 --bind 0.0.0.0:8000 project.wsgi:application
    volumes:
      - ../../media:/usr/src/app/media
      - ../../static:/usr/src/app/static
    ports:
      - 8085:8000
    env_file:
      - .env
      - .env.secret
    depends_on:
      - db
      - rabbitmq
    restart: always
  celery:
    build:
      context: ../../
      dockerfile: ./Docker/prod/python/Dockerfile
      target: celery
    command: celery -A project worker -l info
    volumes:
      - ../../media:/usr/src/app/media
    env_file:
      - .env
      - .env.secret
    depends_on:
      - db
      - rabbitmq
    restart: always

volumes:
  postgres_data:
