# Generated by Django 2.1.2 on 2018-11-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181023_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceswapimage',
            name='status',
            field=models.TextField(choices=[('queued', 'Queued'), ('success', 'Success'), ('error', 'Error')], default='queued'),
        ),
        migrations.AddField(
            model_name='faceswapimage',
            name='status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faceswapimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
