# Generated by Django 2.1.7 on 2019-02-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181120_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceswapimage',
            name='user',
        ),
    ]
